src/WebApp/Controllers/LevelsController.cs
using Fluorite.Strainer.Models;
using Microsoft.AspNetCore.Mvc;
using ParkingLot.Application;
using ParkingLot.Application.Levels.InputModels;
using ParkingLot.Application.Levels.Queries;
using ParkingLot.Application.Levels.Repositories;
using ParkingLot.Application.Levels.ViewModels;
using ParkingLot.Application.Notifications.Models;
using ParkingLot.Application.Notifications.Storages.Abstractions;
using ParkingLot.Application.Pagination.Managers;
using ParkingLot.Application.Spaces.Queries;
using ParkingLot.Application.Spaces.Repositories;
using ParkingLot.Application.Spaces.ViewModels;
using ParkingLot.Domain.Levels;
using ParkingLot.Domain.Spaces;
using ParkingLot.Extensions.Notifications;
using System.Threading.Tasks;

namespace ParkingLot.WebApp.Controllers;

public class LevelsController : Controller
{
    private readonly INotificationStorage _notificationStorage;
    private readonly IPaginationManager<Level, LevelListItemVM> _levelsPaginationManager;
    private readonly IPaginationManager<Space, SpaceListItemVM> _spacesPaginationManager;
    private readonly ILevelsRepository _levelsRepository;
    private readonly ISpacesRepository _spacesRepository;
    private readonly IGetHighestSpaceNumberQuery _getHighestSpaceNumberQuery;
    private readonly IGetLevelDetailsQuery _getLevelDetailsQuery;
    private readonly IGetUpdateLevelInputModelQuery _getUpdateLevelViewModelQuery;
    private readonly ICheckAllLevelSpacesAreUnoccupiedQuery _checkAllLevelSpacesAreUnoccupiedQuery;
    private readonly IUnitOfWork _unitOfWork;

    public LevelsController(
        INotificationStorage notificationStorage,
        IPaginationManager<Level, LevelListItemVM> levelsPaginationManager,
        IPaginationManager<Space, SpaceListItemVM> spacesPaginationManager,
        ILevelsRepository levelsRepository,
        ISpacesRepository spacesRepository,
        IGetHighestSpaceNumberQuery getHighestSpaceNumberQuery,
        IGetLevelDetailsQuery getLevelDetailsQuery,
        IGetUpdateLevelInputModelQuery getUpdateLevelViewModelQuery,
        ICheckAllLevelSpacesAreUnoccupiedQuery checkAllLevelSpacesAreUnoccupiedQuery,
        IUnitOfWork unitOfWork)
    {
        _notificationStorage = notificationStorage;
        _levelsPaginationManager = levelsPaginationManager;
        _spacesPaginationManager = spacesPaginationManager;
        _levelsRepository = levelsRepository;
        _spacesRepository = spacesRepository;
        _getHighestSpaceNumberQuery = getHighestSpaceNumberQuery;
        _getLevelDetailsQuery = getLevelDetailsQuery;
        _getUpdateLevelViewModelQuery = getUpdateLevelViewModelQuery;
        _checkAllLevelSpacesAreUnoccupiedQuery = checkAllLevelSpacesAreUnoccupiedQuery;
        _unitOfWork = unitOfWork;
    }

    [HttpGet]
    public async Task<IActionResult> Index([FromQuery] StrainerModel strainerModel)
    {
        var result = await _levelsPaginationManager.GetPagedAsync(strainerModel);

        return View(result);
    }

    [HttpGet("[controller]/{id:int}")]
    public async Task<IActionResult> Show([FromRoute] int id)
    {
        var viewModel = await _getLevelDetailsQuery.GetAsync(id);
        if (viewModel == null)
        {
            return NotFound();
        }

        return View(viewModel);
    }

    [HttpGet]
    public IActionResult New()
    {
        return View(new CreateLevelInputModel());
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromForm] CreateLevelInputModel inputModel)
    {
        var level = new Level(inputModel.Position.Value);

        // Get last space number.
        var lastSpaceNumber = await _getHighestSpaceNumberQuery.GetAsync();

        // Create related spaces.
        for (int i = 0; i < inputModel.SpacesAmount; i++)
        {
            var space = new Space
            {
                Level = level,
                Number = lastSpaceNumber + i + 1,
            };
            _spacesRepository.Add(space);
        }

        _levelsRepository.Add(level);

        await _unitOfWork.SaveChangesAsync();

        _notificationStorage.Builder()
            .Icon("fas fa-check")
            .Message($"New parking level created.")
            .Title("Success!")
            .Type(NotificationType.Success)
            .SetNotification();

        return RedirectToAction(nameof(Show), new { level.Id });
    }

    [HttpGet("[controller]/{id:int}/[action]")]
    public async Task<IActionResult> Edit([FromRoute] int id)
    {
        var viewModel = await _getUpdateLevelViewModelQuery.GetAsync(id);
        if (viewModel == null)
        {
            return NotFound();
        }

        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Update([FromForm] UpdateLevelInputModel inputModel)
    {
        var model = await _levelsRepository.FindAsync(inputModel.Id.Value);
        if (model == null)
        {
            return NotFound();
        }

        model.SetPosition(inputModel.Position.Value);

        await _unitOfWork.SaveChangesAsync();

        _notificationStorage.Builder()
            .Icon("fas fa-check")
            .Message("Parking level updated.")
            .Title("Success!")
            .Type(NotificationType.Success)
            .SetNotification();

        return RedirectToAction(nameof(Show), new { model.Id });
    }

    [HttpPost]
    public async Task<IActionResult> Destroy([FromForm] DeleteLevelInputModel viewModel)
    {
        var level = await _levelsRepository.FindAsync(viewModel.Id.Value);
        if (level is null)
        {
            return NotFound();
        }

        if (!await _checkAllLevelSpacesAreUnoccupiedQuery.CheckAsync(viewModel.Id.Value))
        {
            return BadRequest();
        }

        _levelsRepository.Remove(level);

        await _unitOfWork.SaveChangesAsync();

        _notificationStorage.Builder()
            .Icon("fas fa-check")
            .Message($"Parking level removed.")
            .Title("Success!")
            .Type(NotificationType.Success)
            .SetNotification();

        return RedirectToAction(nameof(Index));
    }
}

src/WebApp/Controllers/SpacesController.cs
using Fluorite.Strainer.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using ParkingLot.Application;
using ParkingLot.Application.Notifications.Models;
using ParkingLot.Application.Notifications.Storages.Abstractions;
using ParkingLot.Application.Pagination.Managers;
using ParkingLot.Application.Spaces.InputModels;
using ParkingLot.Application.Spaces.Queries;
using ParkingLot.Application.Spaces.Repositories;
using ParkingLot.Application.Spaces.ViewModels;
using ParkingLot.Domain.Spaces;
using ParkingLot.Extensions.Notifications;
using System.Threading.Tasks;

namespace ParkingLot.WebApp.Controllers;

public class SpacesController : Controller
{
    private readonly ISpacesRepository _spacesRepository;
    private readonly IUnitOfWork _unitOfWork;
    private readonly IPaginationManager<Space, SpaceListItemVM> _spacesPaginationManager;
    private readonly IStringLocalizer<SpacesController> _localizer;
    private readonly INotificationStorage _notificationStorage;
    private readonly IGetSpaceDetailsQuery _getSpaceDetailsQuery;
    private readonly IGetUpdateSpaceInputModelQuery _getUpdateSpaceViewModelQuery;
    private readonly ICheckSpaceWithNumberExistsQuery _checkSpaceWithNumberExistsQuery;
    private readonly ICheckSpaceIsCurrentlyOccupiedQuery _checkSpaceIsCurrentlyOccupiedQuery;

    public SpacesController(
        INotificationStorage notificationStorage,
        IGetSpaceDetailsQuery getSpaceDetailsQuery,
        IGetUpdateSpaceInputModelQuery getUpdateSpaceViewModelQuery,
        ICheckSpaceWithNumberExistsQuery checkSpaceWithNumberExistsQuery,
        ICheckSpaceIsCurrentlyOccupiedQuery checkSpaceIsCurrentlyOccupiedQuery,
        IPaginationManager<Space, SpaceListItemVM> spacesPaginationManager,
        IStringLocalizer<SpacesController> stringLocalizer,
        ISpacesRepository spacesRepository,
        IUnitOfWork unitOfWork)
    {
        _notificationStorage = notificationStorage;
        _getSpaceDetailsQuery = getSpaceDetailsQuery;
        _getUpdateSpaceViewModelQuery = getUpdateSpaceViewModelQuery;
        _checkSpaceWithNumberExistsQuery = checkSpaceWithNumberExistsQuery;
        _checkSpaceIsCurrentlyOccupiedQuery = checkSpaceIsCurrentlyOccupiedQuery;
        _spacesPaginationManager = spacesPaginationManager;
        _localizer = stringLocalizer;
        _spacesRepository = spacesRepository;
        _unitOfWork = unitOfWork;
    }

    [HttpGet]
    public async Task<IActionResult> Index([FromQuery] StrainerModel strainerModel)
    {
        var pagedResult = await _spacesPaginationManager.GetPagedAsync(strainerModel);

        return View(pagedResult);
    }

    [HttpGet("[controller]/{id:int}")]
    public async Task<IActionResult> Show([FromRoute] int id)
    {
        var viewModel = await _getSpaceDetailsQuery.GetAsync(id);
        if (viewModel == null)
        {
            return NotFound();
        }

        return View(viewModel);
    }

    [HttpGet]
    public IActionResult New(int? id)
    {
        var viewModel = new CreateSpaceInputModel
        {
            LevelId = id ?? default,
        };

        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Create([FromForm] CreateSpaceInputModel inputModel)
    {
        if (!ModelState.IsValid)
        {
            Response.StatusCode = StatusCodes.Status400BadRequest;

            return View(nameof(New), inputModel);
        }

        if (await _checkSpaceWithNumberExistsQuery.CheckAsync(inputModel.Number.Value))
        {
            Response.StatusCode = StatusCodes.Status400BadRequest;
            ModelState.AddModelError(
                "SpaceNumberAlreadyTaken",
                _localizer.GetString("SpaceNumberAlreadyTaken", inputModel.Number));

            return View(nameof(New), inputModel);
        }

        var model = new Space
        {
            IsForHandicapped = inputModel.IsForHandicapped,
            LevelId = inputModel.LevelId.Value,
            Number = inputModel.Number.Value,
            Status = inputModel.Status.Value,
        };

        _spacesRepository.Add(model);

        await _unitOfWork.SaveChangesAsync();

        _notificationStorage.Builder()
            .Icon("fas fa-check")
            .Message("New parking space created.")
            .Title("Success!")
            .Type(NotificationType.Success)
            .SetNotification();

        return RedirectToAction(nameof(Show), new { model.Id });
    }

    [HttpGet("[controller]/{id:int}/[action]")]
    public async Task<IActionResult> Edit([FromRoute] int id)
    {
        var viewModel = await _getUpdateSpaceViewModelQuery.GetAsync(id);
        if (viewModel == null)
        {
            return NotFound();
        }

        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Update([FromForm] UpdateSpaceInputModel inputModel)
    {
        if (!ModelState.IsValid)
        {
            Response.StatusCode = StatusCodes.Status400BadRequest;

            return View(nameof(Edit), inputModel);
        }

        var model = await _spacesRepository.FindAsync(inputModel.Id.Value);
        if (model == null)
        {
            return NotFound();
        }

        if (await _checkSpaceWithNumberExistsQuery.CheckAsync(inputModel.Number.Value, inputModel.Id.Value))
        {
            Response.StatusCode = StatusCodes.Status400BadRequest;
            ModelState.AddModelError(
                "SpaceNumberAlreadyTaken",
                _localizer.GetString("SpaceNumberAlreadyTaken", inputModel.Number));

            return View(nameof(Edit), inputModel);
        }

        model.IsForHandicapped = inputModel.IsForHandicapped;
        model.LevelId = inputModel.LevelId.Value;
        model.Number = inputModel.Number.Value;
        model.Status = inputModel.Status.Value;

        _spacesRepository.Update(model);

        await _unitOfWork.SaveChangesAsync();

        _notificationStorage.Builder()
            .Icon("fas fa-check")
            .Message("Parking space updated.")
            .Title("Success!")
            .Type(NotificationType.Success)
            .SetNotification();

        return RedirectToAction(nameof(Show), new { model.Id });
    }

    [HttpPost]
    public async Task<IActionResult> Destroy([FromForm] DeleteSpaceInputModel viewModel)
    {
        var space = await _spacesRepository.FindAsync(viewModel.Id.Value);
        if (space is null)
        {
            return NotFound();
        }

        if (await _checkSpaceIsCurrentlyOccupiedQuery.CheckAsync(viewModel.Id.Value))
        {
            ModelState.AddModelError("SpaceRemoval", _localizer.GetString("CannotRemoveSpaceCurrentlyOccupied"));

            return BadRequest();
        }

        _spacesRepository.Remove(space);

        await _unitOfWork.SaveChangesAsync();

        _notificationStorage.Builder()
            .Icon("fas fa-check")
            .Message($"Parking space removed.")
            .Title("Success!")
            .Type(NotificationType.Success)
            .SetNotification();

        return RedirectToAction(nameof(Index));
    }
}

src/WebApp/Views/Spaces/Edit.cshtml
@inject ISelectListProvider<Level> SelectListProvider
@model UpdateSpaceInputModel
@{
    ViewBag.Title = Localizer.GetString("Title");
    var levelsSelectList = await SelectListProvider.GetSelectListAsync(Model.LevelId);
    var statusSelectList = Html.GetEnumSelectList<SpaceStatus>();
}

<div class="row">
    <div class="col">
        <h1 class="display-4 text-center break-word">@ViewBag.Title</h1>
    </div>
</div>

<hr class="margin-y-lg" />

<div class="row margin-bottom-sm">
    <div class="col">
        <a asp-action="@nameof(SpacesController.Show)" asp-route-id="@Model.Id" class="btn btn-primary float-left">
            <i class="fas fa-chevron-left padding-right-sm"></i>
            @Localizer.GetString("Back")
        </a>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6 justify-content-center">
        <form asp-action="@nameof(SpacesController.Update)">

            <partial name="_Errors/_ValidationSummary" />

            <div class="form-group">
                <label asp-for="Number"></label>
                <input asp-for="Number" class="form-control">
                <span asp-validation-for="Number"></span>
                <div>
                    <small>@Localizer.GetString("Number_Description")</small>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Status"></label>
                <select asp-for="Status" asp-items="@statusSelectList" class="custom-select"></select>
                <span asp-validation-for="Status"></span>
            </div>

            <div class="form-group">
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" asp-for="IsForHandicapped">
                    <label class="custom-control-label" asp-for="IsForHandicapped"></label>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="LevelId"></label>
                <select asp-for="LevelId" asp-items="@levelsSelectList" class="custom-select"></select>
                <span asp-validation-for="LevelId"></span>
                <div>
                    <small>@Localizer.GetString("LevelId_Description")</small>
                </div>
            </div>

            <button class="btn btn-success btn-lg" type="submit">
                <i class="fas fa-check padding-right-sm"></i>
                @Localizer.GetString("Submit")
            </button>

            <input asp-for="Id" hidden />

        </form>
    </div>
</div>

@section Scripts {
    <partial name="_Scripts\_ValidationScripts" />
}

src/WebApp/Views/Spaces/Index.cshtml
@model IPagedResult<SpaceListItemVM>
@{
    Layout = "_Layouts/_LayoutFluid1400";
    ViewBag.Title = Localizer.GetString("Title");
}

<div class="row">
    <div class="col">
        <h1 class="display-4 text-center break-word">@ViewBag.Title</h1>
    </div>
</div>

<hr class="margin-y-lg" />

<div class="row margin-bottom-sm">
    <div class="col">
        <a asp-action="@nameof(SpacesController.New)" class="btn btn-success float-right">
            <i class="fas fa-plus padding-right-sm"></i>
            @Localizer.GetString("New")
        </a>
    </div>
</div>

<partial name="_ListView/_Head" />

<div class="row">
    <div class="col col-2">
        <partial name="_ListView/_Filtering/_FiltersSelector" />
    </div>
    <div class="col col-10">
        <table class="table table-hover vertical-align text-center">
            <partial name="_TableHead" model="Model.Items.FirstOrDefault()" />
            <tbody>
                @foreach (var item in Model.Items)
                {
                    <partial name="_TableRow" model="item" />
                }
            </tbody>
        </table>
    </div>
</div>

<partial name="_ListView/_Footer" />

<partial name="_Modals/_RemoveSpaceConfirmation" model="null" />

@section Scripts {
    <script>
        $('button[data-target="#removeSpaceConfirmation"]').click(function () {
            let id = $(this).attr('data-id');
            $('#removeSpaceConfirmation').find('input#Id').val(id);
        });
    </script>
}

src/WebApp/Views/Spaces/New.cshtml
@inject ISelectListProvider<Level> SelectListProvider
@model CreateSpaceInputModel
@{
    ViewBag.Title = Localizer.GetString("Title");
    var levelsSelectList = await SelectListProvider.GetSelectListAsync(Model.LevelId);
    var statusSelectList = Html.GetEnumSelectList<SpaceStatus>();
}

<div class="row">
    <div class="col">
        <h1 class="display-4 text-center break-word">@ViewBag.Title</h1>
    </div>
</div>

<hr class="margin-y-lg" />

<div class="row margin-bottom-sm">
    <div class="col">
        <a asp-action="@nameof(SpacesController.Index)" class="btn btn-primary float-left">
            <i class="fas fa-chevron-left padding-right-sm"></i>
            @Localizer.GetString("Back")
        </a>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6 justify-content-center">
        <form asp-action="@nameof(SpacesController.Create)">

            <partial name="_Errors/_ValidationSummary" />

            <div class="form-group">
                <label asp-for="Number"></label>
                <input asp-for="Number" class="form-control">
                <span asp-validation-for="Number"></span>
                <div>
                    <small>@Localizer.GetString("Number_Description")</small>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Status"></label>
                <select asp-for="Status" asp-items="@statusSelectList" class="custom-select"></select>
                <span asp-validation-for="Status"></span>
            </div>

            <div class="form-group">
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" asp-for="IsForHandicapped">
                    <label class="custom-control-label" asp-for="IsForHandicapped"></label>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="LevelId"></label>
                <select asp-for="LevelId" asp-items="@levelsSelectList" class="custom-select">
                    <option selected disabled>Select parking level</option>
                </select>
                <span asp-validation-for="LevelId"></span>
                <div>
                    <small>@Localizer.GetString("LevelId_Description")</small>
                </div>
            </div>
            <button class="btn btn-success btn-lg" type="submit">
                <i class="fas fa-check padding-right-sm"></i>
                @Localizer.GetString("Submit")
            </button>

        </form>
    </div>
</div>

@section Scripts {
    <partial name="_Scripts\_ValidationScripts" />
}

src/WebApp/Views/Spaces/Show.cshtml
@model SpaceVM
@{
    ViewBag.Title = Localizer.GetString("Title", Model.Id);
}

<div class="row">
    <div class="col">
        <h1 class="display-4 text-center break-word">@ViewBag.Title</h1>
    </div>
</div>

<hr class="margin-y-lg" />

<div class="row margin-bottom-sm">
    <div class="col">
        <a asp-action="@nameof(SpacesController.Index)"
           class="btn btn-primary float-left">
            <i class="fas fa-chevron-left padding-right-sm"></i>
            @Localizer.GetString("Back")
        </a>

        <button class="btn btn-danger ml-2 float-right"
                data-toggle="modal"
                data-target="#removeSpaceConfirmation">
            <i class="fas fa-trash-alt padding-right-xs"></i>
            @Localizer.GetString("Remove")
        </button>
        <a class="btn btn-success float-right"
           asp-action="@nameof(SpacesController.Edit)"
           asp-route-id="@Model.Id">
            <i class="fas fa-pencil-alt padding-right-xs"></i>
            @Localizer.GetString("Edit")
        </a>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6 justify-content-center">
        <dl class="row">
            <dt class="col">@Html.DisplayNameFor(m => m.Id):</dt>
            <dd class="col">@Html.DisplayFor(m => m.Id)</dd>
        </dl>
        <dl class="row">
            <dt class="col">@Html.DisplayNameFor(m => m.Number):</dt>
            <dd class="col">@Html.DisplayFor(m => m.Number)</dd>
        </dl>
        <dl class="row">
            <dt class="col">@Html.DisplayNameFor(m => m.LevelPosition):</dt>
            <dd class="col">
                <a class="btn btn-sm btn-primary"
                   asp-controller="Levels"
                   asp-action="@nameof(LevelsController.Show)"
                   asp-route-id="@Model.LevelId">
                    <i class="fas fa-layer-group padding-right-xs"></i>
                    @Html.DisplayFor(m => m.LevelPosition)
                </a>
            </dd>
        </dl>
        <dl class="row">
            <dt class="col">@Html.DisplayNameFor(m => m.IsOccupied):</dt>
            <dd class="col">
                <span class="@(Model.IsOccupied ? "text-danger" : "text-success")">
                    @Html.DisplayFor(m => m.IsOccupied, "BoolYesNo")
                </span>
            </dd>
        </dl>
        <dl class="row">
            <dt class="col">@Html.DisplayNameFor(m => m.IsOutOfService):</dt>
            <dd class="col">
                <span class="@(Model.IsOutOfService ? "bg-danger rounded px-2 py-1" : "text-success")">
                    @Html.DisplayFor(m => m.IsOutOfService, "BoolYesNo")
                </span>
            </dd>
        </dl>
        <dl class="row">
            <dt class="col">@Html.DisplayNameFor(m => m.IsForHandicapped):</dt>
            <dd class="col">
                <span class="@(Model.IsForHandicapped ? "bg-primary rounded px-2 py-1" : null)">
                    @Html.DisplayFor(m => m.IsForHandicapped, "BoolYesNo")
                </span>
            </dd>
        </dl>
        <dl class="row">
            <dt class="col">@Html.DisplayNameFor(m => m.Created):</dt>
            <dd class="col">
                <span title="@Html.DisplayTextFor(m => m.Created)">
                    @Html.DisplayFor(m => m.Created)
                </span>
            </dd>
        </dl>
        <dl class="row">
            <dt class="col">@Html.DisplayNameFor(m => m.Updated):</dt>
            <dd class="col">
                <span title="@Html.DisplayTextFor(m => m.Updated)">
                    @Html.DisplayFor(m => m.Updated)
                </span>
            </dd>
        </dl>
        <div class="row">
            <div class="col">
                <hr />

                <div class="pb-2">
                    <h3 class="text-center">
                        @Localizer.GetString("LastSpaceHistoryEntries")
                    </h3>

                    <a class="d-block text-right" href="@(Url.Action(
                        nameof(HistoryController.Spaces),
                        "History")
                        + "?Filters="
                        + "Space.Number"
                        + "=="
                        + Model.Number)">
                        <i class="fas fa-history pr-1"></i>
                        @Localizer.GetString("FullHistory")
                    </a>
                </div>

                <table class="table table-hover vertical-align text-center">
                    <partial name="_SpaceHistory/_TableHead" model="Model.RecentHistory.FirstOrDefault()" />
                    <tbody>
                        @foreach (var item in Model.RecentHistory)
                        {
                            <partial name="_SpaceHistory/_TableRow" model="item" />
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<partial name="_Modals/_RemoveSpaceConfirmation" model="Model.Id" />