src/WebApp/Controllers/LoggingController.cs
using AutoMapper;
using CSharpFunctionalExtensions;
using Fluorite.Strainer.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using ParkingLot.Application.Logging.InputModels;
using ParkingLot.Application.Logging.Requests;
using ParkingLot.Application.Logging.ViewModels;
using ParkingLot.Application.Pagination.Managers;
using ParkingLot.Domain.Logging;
using ParkingLot.WebApp.Controllers.Abstract;
using System.Threading.Tasks;

namespace ParkingLot.WebApp.Controllers;

public class LoggingController : ResultsControllerBase
{
    private readonly IMapper _mapper;
    private readonly IMediator _mediator;
    private readonly IPaginationManager<RequestLog, RequestLogVM> _requestLogsPaginationManager;

    public LoggingController(
        IMapper mapper,
        IMediator mediator,
        IPaginationManager<RequestLog, RequestLogVM> requestLogsPaginationManager)
    {
        _mapper = mapper;
        _mediator = mediator;
        _requestLogsPaginationManager = requestLogsPaginationManager;
    }

    [HttpGet]
    public async Task<IActionResult> Index([FromQuery] StrainerModel strainerModel)
    {
        var pagedResult = await _requestLogsPaginationManager.GetPagedAsync(strainerModel);

        return View(pagedResult);
    }

    [Route("[controller]/Charts/Requests")]
    [HttpGet]
    public async Task<IActionResult> Chart()
    {
        return await Result.Success()
            .Map(() => new GetRequestLogsCountRequest())
            .Map(async request => await _mediator.Send(request))
            .Finally(result => BuildViewResult(result, "Charts/Requests"));
    }

    [HttpGet("[controller]/{id:int}")]
    public Task<IActionResult> Show([FromRoute] int id)
    {
        return Result.Success()
            .Map(() => new GetRequestLogDetailsRequest() { Id = id })
            .Bind(request => _mediator.Send(request))
            .Finally(BuildViewResult);
    }

    [HttpPost]
    public Task<IActionResult> Destroy([FromForm] DeleteRequestLogInputModel inputModel)
    {
        return Result.Success()
            .Map(() => _mapper.Map<DeleteRequestLogRequest>(inputModel))
            .Bind(request => _mediator.Send(request))
            .Finally(result => BuildActionResult(result, onSuccess: () => RedirectToAction(nameof(Index))));
    }
}

src/WebApp/Views/Logging/_Partials/_Modals/_RemoveRequestLogConfirmation.cshtml
@model RequestLogVM

<div class="modal fade" id="removeRequestLogConfirmation" tabindex="-1" role="dialog" aria-labelledby="removeRequestLogConfirmationLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="removeRequestLogConfirmationLabel">
                    @Localizer.GetString("Are you sure?")
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you would like to remove this request log?</p>
            </div>
            <div class="modal-footer">
                <form asp-controller="Logging" asp-action="@nameof(LoggingController.Destroy)">
                    <button type="submit" class="btn btn-danger">
                        <i class="fas fa-trash-alt padding-right-xs"></i>
                        @Localizer.GetString("Remove")
                    </button>
                    <input asp-for="Id" hidden />
                </form>
                <button type="button" class="btn btn-primary" data-dismiss="modal">
                    <i class="fas fa-times padding-right-xs"></i>
                    @Localizer.GetString("Cancel")
                </button>
            </div>
        </div>
    </div>
</div>